contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseURL = "http://sobradob.github.io/"
languageCode = "en-us"
title = "Boaz Sobrado"
canonifyurls= true
description="Personal and professional website. Occasional scribbles and scrawls."

